### ISSUE TITLE
Make flexible width input field for the page number

### ISSUE THREAD

**Issue by rybakit** [basis-company/tarantool-admin#12]
Currently, big page numbers are not fully displayed which confuse users. For example, on the screenshot below the current page is 175, not 75:

![pagination](https://user-images.githubusercontent.com/533861/29311308-b906778e-81b1-11e7-8ec4-a523f7598c98.png)

**Comment by nekufa** [comment]
@rybakit, please checkout latest version.
now, it's not flexible, but width is ok.

in addition, you can change page size:
![image](https://user-images.githubusercontent.com/405067/29332116-8f5dd2a0-8207-11e7-8c9e-90494eff622e.png)

Is it ok? Or you need flexible width for current page

**Comment by rybakit** [comment]
Yep, the latest version looks better, at least now it can display 5-digit page number without cropping, which is enough in most of the cases, I guess.
