### ISSUE TITLE
Some field values are not displayed correctly in the "update" popup

### ISSUE THREAD

**Issue by rybakit** [basis-company/tarantool-admin#17]
![tnt_admin_update2](https://user-images.githubusercontent.com/533861/31945708-3934b394-b8d0-11e7-99fa-0ac51b939329.png)
![tnt_admin_update2_format](https://user-images.githubusercontent.com/533861/31945710-3b4eebf4-b8d0-11e7-801e-208ec42cc67b.png)

**Comment by nekufa** [comment]
fixed in latest release

**Comment by rybakit** [comment]
👍  thanks!
