### ISSUE TITLE
server-side connection management

### ISSUE THREAD

**Issue by nekufa** [basis-company/tarantool-admin#18]
It will be good to define connections for tarantool-admin container. They will be predefined and user will not configure connections manually.

I see two ways to define connections:

1. Environment variable TARANTOOL_CONNECTIONS = user:pass@host:port;user:pass@host:port
2. Put the file /var/www/html/connections.php that should return an array of connection strings.

What is the best way? Should we implement all of them?
Maybe there are other ways?

Anybody wants to have an option to make connection-list read only?
I mean they are defined on server and can't be changed through web ui.

**Comment by aensidhe** [comment]
> Anybody wants to have an option to make connection-list read only?

Yes, I would like have this option.

> user:pass@host:port;user:pass@host:port

Good option, because it's identical to replication source format of tarantool.

**Comment by nekufa** [comment]
> Good option, because it's identical to replication source format of tarantool.

Tarantool docker image uses comma-separated values, instead of semicolon.  
It's a good idea to use same format, thanks!

**Comment by nekufa** [comment]
fixed in 0.2.35 (latest container build).

**Comment by nekufa** [comment]
@aensidhe 
* TARANTOOL_CONNECTIONS - comma-separated connection strings
* TARANTOOL_CONECTIONS_READONLY - disable connections editor
