### ISSUE TITLE
Edit boolean fields

### ISSUE THREAD

**Issue by aensidhe** [basis-company/tarantool-admin#19]
1. Create a space
2. Insert a tuple with boolean field.
3. Try to edit it through admin.

Is it possible to provide a checkbox?

Space: 
![image](https://user-images.githubusercontent.com/3948027/35516002-a8f8a3a6-051b-11e8-83de-a78b3195ff94.png)

Edit error:
![image](https://user-images.githubusercontent.com/3948027/35516026-b8004f48-051b-11e8-940f-c1798cc06985.png)

**Comment by nekufa** [comment]
Hello, sure!

**Comment by nekufa** [comment]
implemented in 0.2.42
