### ISSUE TITLE
Can't create index in space without format

### ISSUE THREAD

**Issue by trollsid** [basis-company/tarantool-admin#21]
Can't create index in space without format, showing is an error message:
`Ext.JSON.decode(): You're trying to decode an invalid JSON String: <br>
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/html/php/Job/Space/CreateIndex.php</b> on line <b>20</b><br>
{"success":false,"message":"Illegal parameters, options.parts must have at least one part","trace":["#0 \/var\/www\/html\/vendor\/tarantool\/client\/src\/Client.php(137): Tarantool\\Client\\Packer\\PurePacker-&gt;unpack('\\x83\\x00\\xCE\\x00\\x00\\x80\\x01\\x01\\xCF\\x00\\x00\\x00\\x00\\x00\\x00...')","#1 \/var\/www\/html\/vendor\/tarantool\/mapper\/src\/Client.php(43): Tarantool\\Client\\Client-&gt;sendRequest(Object(Tarantool\\Client\\Request\\EvaluateRequest))","#2 \/var\/www\/html\/vendor\/tarantool\/client\/src\/Client.php(120): Tarantool\\Mapper\\Client-&gt;sendRequest(Object(Tarantool\\Client\\Request\\EvaluateRequest))","#3 \/var\/www\/html\/vendor\/tarantool\/mapper\/src\/Space.php(167): Tarantool\\Client\\Client-&gt;evaluate('box.space[515]:...', Array)","#4 \/var\/www\/html\/php\/Job\/Space\/CreateIndex.php(28): Tarantool\\Mapper\\Space-&gt;createIndex(Array)","#5 [internal function]: Job\\Space\\CreateIndex-&gt;run()","#6 \/var\/www\/html\/vendor\/league\/container\/src\/ReflectionContainer.php(74): ReflectionMethod-&gt;invokeArgs(Object(Job\\Space\\CreateIndex), Array)","#7 \/var\/www\/html\/vendor\/league\/container\/src\/Container.php(211): League\\Container\\ReflectionContainer-&gt;call(Array, Array)","#8 \/var\/www\/html\/vendor\/basis-company\/framework\/src\/Runner.php(93): League\\Container\\Container-&gt;call(Array)","#9 \/var\/www\/html\/php\/Controller\/Admin.php(37): Basis\\Runner-&gt;dispatch('space.createind...', Array)","#10 [internal function]: Controller\\Admin-&gt;api(Object(Basis\\Runner))","#11 \/var\/www\/html\/vendor\/league\/container\/src\/ReflectionContainer.php(74): ReflectionMethod-&gt;invokeArgs(Object(Controller\\Admin), Array)","#12 \/var\/www\/html\/vendor\/league\/container\/src\/Container.php(211): League\\Container\\ReflectionContainer-&gt;call(Array, Array)","#13 \/var\/www\/html\/vendor\/basis-company\/framework\/src\/Http.php(47): League\\Container\\Container-&gt;call(Array, Array)","#14 \/var\/www\/html\/server.php(12): Basis\\Http-&gt;process('\/admin\/api')","#15 {main}"]}`

**Comment by nekufa** [comment]
use 0.2.49
