### ISSUE TITLE
without Docker

### ISSUE THREAD

**Issue by SWSAmor** [basis-company/tarantool-admin#22]
Very good initiation, thank you. But i need a dockerless install guide. Would you make one?

I installed it under Lighty but i got 404 for /admin/api. What should that be link to? Thx.

**Comment by nekufa** [comment]
Hello, 
Thanks, i will add this case to documentation.

If you need it ASAP, follow these steps:
- Install apache with mod_php.
- Clone repository in your virtual host home directory (default /var/www/html)
- install composer
- install external dependencies
- copy .htaccess and server.php from framework/resources folder

This scenario you can find in Dockerfile:
https://github.com/basis-company/tarantool-admin/blob/master/Dockerfile#L13-L27

**Comment by SWSAmor** [comment]
Based on your help i could install it under Lighttpd. Thank you. :-)
