### ISSUE TITLE
Please add a favicon

### ISSUE THREAD

**Issue by rybakit** [basis-company/tarantool-admin#23]
Now, it's hard to find the tarantool-admin tab if you have many other tabs open:
![tnt_admin_favicon](https://user-images.githubusercontent.com/533861/39127682-063c8c2c-4706-11e8-9bda-750e63800800.png)

**Comment by nekufa** [comment]
Good idea, do you have any ideas what can be used?
I think tarantool official logo will be missleading

**Comment by rybakit** [comment]
![tarantool-admin-logo-small](https://user-images.githubusercontent.com/533861/39156475-8b873e18-4756-11e8-89d0-6ffca592f664.png) :smile:

**Comment by nekufa** [comment]
are you serious? :grinning:

**Comment by rybakit** [comment]
> are you serious?

yep, I think it's awesome :) Another option:

![tarantool-admin-hummer](https://user-images.githubusercontent.com/533861/39176281-b6119006-47ac-11e8-9f64-f541348bdf5a.png)

**Comment by nekufa** [comment]
The first one is the winner :)

**Comment by nekufa** [comment]
Thanks, added in 0.3.6 version
