### ISSUE TITLE
Enhance query's result rendering

### ISSUE THREAD

**Issue by rybakit** [basis-company/tarantool-admin#24]
Would be good to provide the "pretty print" tab/checkbox for json-like results. Now it's a bit messy:

![tnt_query_result](https://user-images.githubusercontent.com/533861/39306033-4cabd856-495f-11e8-8b6b-112923d24c62.png)

**Comment by nekufa** [comment]
hm, json can be nested, looks like it should be a tree

**Comment by rybakit** [comment]
> hm, json can be nested, looks like it should be a tree

Here is a FF screenshot for inspiration:

![ff_json](https://user-images.githubusercontent.com/533861/39570407-8c189e02-4ec8-11e8-951d-3b8a301bea1b.png)

**Comment by nekufa** [comment]
yep, thanks, i agree it should look like this one
