### ISSUE TITLE
Popup resizing issues

### ISSUE THREAD

**Issue by rybakit** [basis-company/tarantool-admin#26]
Seems like resizing doesn't work properly. Checked in FF:
![tnt_admin_edit_popup2](https://user-images.githubusercontent.com/533861/40657190-38d946ea-6347-11e8-80d0-1ce0a8a901ae.png)
![tnt_admin_edit_popup](https://user-images.githubusercontent.com/533861/40657191-38f8c4fc-6347-11e8-89a4-5ef7b3520bf3.png)

**Comment by rybakit** [comment]
> what behaviour do you expect on the first screenshot?

I would expect no empty space before labels. But my main concern is more about the second screenshot. Would be great to resize the inner container (form) to 100% of its parent (modal) to show more data in inputs.

**Comment by nekufa** [comment]
okay, i will investigate this one!

**Comment by nekufa** [comment]
we have an ability to split fields into columns so they will fit the screen.  
so, it's hard to implement dynamic field label width right now  
i hope it's not so important, so i will fix second case only  
if you need dynamic label width width, please, create new ticket  

![image](https://user-images.githubusercontent.com/405067/40681737-a9b44446-6392-11e8-8717-93a02b0d98f1.png)
