### ISSUE TITLE
Error in latest docker build

### ISSUE THREAD

**Issue by BigJoe01** [basis-company/tarantool-admin#30]
Hi,

After creating new space and addig first property i get php error message.
Latest docker build.
Latest tarantool docker build, default install.

Ext.JSON.decode(): You're trying to decode an invalid JSON String: 
 :  array_merge(): Argument #2 is not an array in 
 /var/www/html/vendor/tarantool/mapper/src/Space.php
 :  array_key_exists() expects parameter 2 to be array, null given in 
 
Regards,

**Comment by nekufa** [comment]
Sorry about that, will fix it asap

**Comment by nekufa** [comment]
Thank you for your report!
Please, checkout 0.3.11 (latest docker image tag)
