### ISSUE TITLE
Broken UI

### ISSUE THREAD

**Issue by makorne** [basis-company/tarantool-admin#32]
``
![screenshot_2019-03-07_06-13-31](https://user-images.githubusercontent.com/26540498/53957950-be6f5d00-40ad-11e9-83a6-acac98e09eb0.png)

**Comment by nekufa** [comment]
Hello, looks like, extjs framework was not loaded.
Do you use docker container or php developer server from console?

**Comment by nekufa** [comment]
Thanks for your feedback, fixed in latest docker build 0.3.13

**Comment by makorne** [comment]
Just re-cloned, docker container.
![Screenshot_2019-03-13_04-28-36](https://user-images.githubusercontent.com/26540498/54264120-bbaab700-4548-11e9-8600-1893915e52b6.png)

**Comment by nekufa** [comment]
Looks like, you still use previous version.
You need force image upgrade using:

`docker pull quay.io/basis-company/tarantool-admin`

**Comment by makorne** [comment]
I try `docker pull quay.io/basis-company/tarantool-admin` - same error

I did  `docker-compose rm --all &&
 docker-compose pull &&
 docker-compose build --no-cache &&
 docker-compose up -d --force-recreate `
- same.

I did in empty directory:
git clone https://github.com/basis-company/tarantool-admin.git 

but looks like it is old docker-compose problem with cache [https://github.com/docker/compose/issues/1049](url)

I did:
`
    docker-compose stop && \
        echo "PikWi says: docker-compose rm ..." && \
    docker-compose rm -f --all && \    
        echo "PikWi says: docker-compose pull" && \
    docker-compose pull && \
        echo "PikWi says: docker-compose build ..." && \
    docker-compose build --no-cache && \
        echo "PikWi says: docker-compose up ..." && \
    docker-compose up -d --force-recreate --remove-orphans` 

But the problem remains.
Maybe  github files are not updated?

docker run -p 8000:80 quay.io/basis-company/tarantool-admin  works normally, no errors.

**Comment by nekufa** [comment]
Please, verify that installer.sh is same as master branch.
If no - git pull and that docker-compose build .
But if you start from scratch - it's very strange.
Please, copy build output to pastebin and share a link for me, it can help me investigating the issue.

By the way, why do you build your own image?
You can use built image in your docker compose file, as well.

**Comment by makorne** [comment]
Looks like I had some issues with docker.  I dropped all several times - containers and images, rebooted and so on..
And now github version works!!!

No special purpose, simply used one of your recommended ways.
Thanks to your team for your work!!

**Comment by makorne** [comment]
After another cleanup of all docker files the error return
[https://www.pastefs.com/pid/105543](url)

**Comment by nekufa** [comment]
So strange, output looks good - everything was built and all assets were downloaded with no issues.  
We use GitHub only for public projects, so i see updates from time to time.  
Sorry, for the delay with answers, can you contact me via [telegram.me/nekufa](http://telegram.me/nekufa)?

**Comment by affair** [comment]
Hi all
@nekufa I have the same error when I move docker-compose.yml file.

I mean if I run ```docker-compose up``` from the root folder of the repo - everything works fine. 

But when I move it up one level and edit docker-compose.yml ```build: .``` replace with ```build: ./tarantool-admin``` I have absolutely the same broken UI. 
How can I solve this issue?
Thanks in advance.

**Comment by nekufa** [comment]
> But when I move it up one level and edit docker-compose.yml `build: .` replace with `build: ./tarantool-admin` I have absolutely the same broken UI.
> How can I solve this issue?

@affair please update volumes as well or simply remove this section.
volumes are configured for hot-code reload if you want to extend the application

**Comment by nekufa** [comment]
@makorne @affair use latest github version, 
i found out what was incorrect, now everything should work good.

**Comment by affair** [comment]
> @makorne @affair use latest github version,
> i found out what was incorrect, now everything should work good.

@nekufa Thanks a lot. It works now
