### ISSUE TITLE
Creating space with dash ("-") in the name make all sorts of things go wrong

### ISSUE THREAD

**Issue by Moskovskiy** [basis-company/tarantool-admin#35]
Space will be created (with error message displayed) and both "Delete" and "Truncate"then will fail to execute.

![image](https://user-images.githubusercontent.com/33791294/59594412-a5147e80-90a8-11e9-995d-d18713253ff5.png)

**Comment by nekufa** [comment]
Hello, thanks for your feedback, use ^0.3.19 version (latest container tag)
