### ISSUE TITLE
support tarantool 2.x

### ISSUE THREAD

**Issue by wormen** [basis-company/tarantool-admin#36]
when do you plan to add support for version 2.x?

**Comment by nekufa** [comment]
Hello!
We use tarantool-admin on multiple versions up to 2.1.2-62 version without any issues
Is there something not working right now?

**Comment by wormen** [comment]
yes, i can not connect

**Comment by nekufa** [comment]
i think connection issue is not related with tarantool version.
please, describe your environment.
how do you run tarantool and tarantool-admin?

**Comment by nekufa** [comment]
reopen if this is actual for you
