### ISSUE TITLE
The string is displayed as a table in query tab

### ISSUE THREAD

**Issue by baltazorbest** [basis-company/tarantool-admin#37]
Hello. 
I was install latest docker images with enable TARANTOOL_DATABASE_QUERY.

In the tab "Query", I wrote the code:

`t = "string"
return type(t)`

And instead of getting "0 string" I got: "0 s, 1 t, ....".
This is clearly visible in the screenshot.

![screenshot](https://user-images.githubusercontent.com/3706041/62694297-5b735080-b9d4-11e9-8af4-db9c2697f4f9.png)

**Comment by nekufa** [comment]
fixed in 0.3.20
