### ISSUE TITLE
Please support Decimal. Tarantool 2.3

### ISSUE THREAD

**Issue by ivan2kh** [basis-company/tarantool-admin#39]
- https://www.tarantool.io/ru/doc/2.2/reference/reference_lua/decimal/
- https://github.com/tarantool/doc/issues/870

**Comment by nekufa** [comment]
@ivan2kh It will be good if you can write any cases why you can't use it right now. 
For example - lua script that creates a space, defines format, insert your data and then you see some issues. Maybe it is not displaying or you can't edit a row, or add new one. What happens? I don't have any issues with decimal because don't use it at all.

**Comment by ivan2kh** [comment]
Here is short example of how decimals are shown.
```
box.cfg{listen=3302}

decimal = require('decimal')
ffi = require('ffi')

_ = box.schema.space.create('test')
_ = box.space.test:create_index('pk')
box.space.test:insert{1, decimal.new(1.1)}

box.schema.user.grant('guest','read,write,execute,create,drop,alter','universe', nil, {if_not_exists=true})
```
![image](https://user-images.githubusercontent.com/7362743/64856265-42d90480-d62a-11e9-8ecc-70033eecb86b.png)

**Comment by nekufa** [comment]
Right now, 2.3 is still not released and there is no docker container for master branch.
So, it's hard to reproduce it right now, let's postpone this task till 2.3 release.

**Comment by maurodelazeri** [comment]
yeaa decimal would be great

**Comment by nekufa** [comment]
0.3.31 (latest docker image tag) release correctly render decimals.
be careful, when you will update it using web interface it will overwrite tuple field with float value.

if you need some logic for decimal updates - please, reopen the ticket and we will investigate it.
right now format is not supported with decimal type.

hope decimal rendering is that you need

**Comment by ivan2kh** [comment]
My respect
