### ISSUE TITLE
Export data from the database.

### ISSUE THREAD

**Issue by kobylinsky-m** [basis-company/tarantool-admin#53]
![image](https://user-images.githubusercontent.com/69149831/97343086-074ad980-18c2-11eb-8661-f42dfc1845cc.png)
Hi! I have a problem when I want to do an export of data that has an "array" format cell. or "map".
![image](https://user-images.githubusercontent.com/69149831/97343425-732d4200-18c2-11eb-942d-d01e0574b2b5.png)

**Comment by nekufa** [comment]
Hello, @Gluyk-1 
Sure - that's why is not clear how to convert array to string.
This can be implemented, do you have any ideas how array should looks like?
Comma-separated or something else?

**Comment by nekufa** [comment]
@kobylinsky-m use version 0.7
complex data is now exporting using json format
