### ISSUE TITLE
Uncaught TypeError: Argument 3 passed to Tarantool\Mapper\Space

### ISSUE THREAD

**Issue by serzius** [basis-company/tarantool-admin#55]
1st 10 mins all work good, then i try create new space as Guest - got error. 
After when click on Spaces tab got error:
Uncaught TypeError: Argument 3 passed to Tarantool\Mapper\Space 

![Снимок-adminui-T](https://user-images.githubusercontent.com/53822039/99081465-e7aaf500-25d3-11eb-9bc9-8a655729f278.PNG)

**Comment by nekufa** [comment]
Hello, is this still actual? Do you have a way to reproduce the error?

**Comment by sarbash** [comment]
The same here:
![изображение](https://user-images.githubusercontent.com/1932297/106917068-f0195480-6718-11eb-9e5c-6c90b3a190e4.png)
The schema:
![изображение](https://user-images.githubusercontent.com/1932297/106917326-353d8680-6719-11eb-851f-ebbcef84820f.png)
Trying to change any field, got the error.

**Comment by nekufa** [comment]
Are you running docker image? What version do you use?

**Comment by sarbash** [comment]
Guess, that might be useful:
```
{
"Id": "sha256:a09cfc2fe309a1a818702110a54d2289e9511393f566b2e3b5a2dd2115882140",
"RepoTags": [
"quay.io/basis-company/tarantool-admin:latest"
],
"RepoDigests": [
"quay.io/basis-company/tarantool-admin@sha256:d07508eafa4d33c7ee01ace69503f8aa936ed74bb3d8af307a176c0e9b3d7001"
],
"Parent": "",
"Comment": "",
"Created": "2020-06-25T11:52:13.121115934Z",
```
version 0.5.15

**Comment by nekufa** [comment]
First of all, looks like, you update dependencies in container.
Please try with fresh unchanged container, use latest 0.6.1 version. 

Maybe it's related with your dataset, please share database snapshot.
If it's hard to share data, add index tab screenshot (how indexes are configured).
Did you describe space schema via admin or try to explore usable database?

**Comment by nekufa** [comment]
@sarbash checkout latest version 0.7.
