### ISSUE TITLE
Support UUID column data view

### ISSUE THREAD

**Issue by chelsEg** [basis-company/tarantool-admin#58]
Hello.

I have error by view space data.

![Error](https://user-images.githubusercontent.com/16079950/106624393-4736f200-657e-11eb-8120-5f2c574df472.png)

I think it's because in my space exist **uuid** column.

Spaces without **uuid** column viewed good!

**Comment by nekufa** [comment]
Hello! 
Right now, I don't have an instance running a database with uuid keys.
Please, share snapshot with this data type and i will check how it can be fixed.

**Comment by chelsEg** [comment]
Create space **test_space**:
```
$mapper->getSchema()->createSpace('test_space', [
    'is_sync'       => true,
    'if_not_exists' => true,
    'engine'        => 'memtx',
    'properties'    => [
        'id'          => 'unsigned',
        'uuid_column' => 'uuid',
    ],
])->addIndex([
    'fields'        => 'id',
    'if_not_exists' => true,
    'sequence'      => true,
]);
```

Save data into **test_space**:
```
use Symfony\Component\Uid\Uuid;

$mapper->getSchema()->getSpace('test_space')->insert([
    null,
    new Uuid('735797ec-4947-4f8d-a238-20341f67ce22')
]);
```

**Comment by nekufa** [comment]
crud for uuid implemented in v. 0.6.0

you can view, update and create tuples with uuid field types
