### ISSUE TITLE
Bugs with delete and find where key type is UUID

### ISSUE THREAD

**Issue by chelsEg** [basis-company/tarantool-admin#60]
Hello.

I have bug with finding by secondary key, where key type is **UUID**.

![find](https://user-images.githubusercontent.com/16079950/107492768-7ad4d600-6b95-11eb-90e4-a3999e55188a.png)

The same bug with deleteting where primary key type is **UUID**.

![delete](https://user-images.githubusercontent.com/16079950/107492787-80cab700-6b95-11eb-8dc7-b0b97cb35878.png)

**Comment by chelsEg** [comment]
Any updates about this task?

I think bug with finding by secondary key, where key type is UUID fixed in #61, but I don't tested this because new version isn't released.

@nekufa can you help with this?

**Comment by nekufa** [comment]
@chelsEg hello! still no updates, the issue is present.
by the way, all fixes were released

**Comment by chelsEg** [comment]
Hmm...
I see #62 merged on 24 Feb, but last release on 3 Feb :)

**Comment by nekufa** [comment]
Yep, but #62 is syntax fix for previous commit simplifying select. 
So it is not related with uuids, just code refactoring

**Comment by chelsEg** [comment]
> Yep, but #62 is syntax fix for previous commit simplifying select.
> So it is not related with uuids, just code refactoring

Yes, but in my project I am using your image from [quay.io](quay.io/basis-company/tarantool-admin) and I'm still using the old code with bug :(

If It's problem, don't worry I'm wait for fix :)

**Comment by nekufa** [comment]
@chelsEg checkout v0.7 with extended uuid support!
