### ISSUE TITLE
/admin/api not answering, app instant loading

### ISSUE THREAD

**Issue by darkfessing** [basis-company/tarantool-admin#80]
Hi there! Pls help to resolve the issue. App is working fine on our standard environment. We use is very often. Thx!

But on closed-isolated-client (btw, system-wide proxy server are used) environment the app not loading. "Pls, wait" on start page, POST hung request to /admin/api. No errors on logs. Zero ideas what could go wrong. Tried different versions, self-rebuilded images, etc.

App launched with standard command: `docker run -p 8000:80 quay.io/basis-company/tarantool-admin` without any envs.

![изображение](https://github.com/user-attachments/assets/071a5830-1dca-42e7-b022-485d3a10153d)
![изображение](https://github.com/user-attachments/assets/3834570e-91b3-4aef-83e2-66d7192d1ecf)
![изображение](https://github.com/user-attachments/assets/53839541-f937-47b9-98b4-144bff5c4737)

Pls help to resolve the issue.

**Comment by darkfessing** [comment]
Fixed here: https://github.com/darkfessing/tarantool-admin/commit/1dc32a9defbb489dac7a535b2cbd6d086bb6ff48

**Comment by nekufa** [comment]
hi @darkfessing, 
looks like backend can't reach the github to check version.

You can disable that feature for private networks via env:
`TARANTOOL_CHECK_VERSION` - default is true. set to false if you want to disable version check
https://github.com/basis-company/tarantool-admin?tab=readme-ov-file#configure-using-env

fix can be applied to admin.configuration job, we need extend context configuration to reduce timeout while fetching version
https://github.com/basis-company/tarantool-admin/blob/master/php/Job/Admin/Configuration.php#L56

**Comment by darkfessing** [comment]
Okay thx!
